# -*- coding: utf-8 -*-
"""06-DateTimeOutputParser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KZ-_L1MTCwVZfn3qRBrKWSAaUxRB_z1V
"""

import os

os.environ["OPENAI_API_KEY"] = "api-key"
os.environ["LANGCHAIN_API_KEY"] = "api-key"
os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGCHAIN_ENDPOINT"] = "http://api.smith.langchain.com"
os.environ["LANGCHAINPROJECT"] = "03-06"

!pip install langchain_openai

from langchain.output_parsers import DatetimeOutputParser
from langchain.prompts import PromptTemplate
from langchain_openai import ChatOpenAI

output_parser = DatetimeOutputParser()
output_parser.format = "%Y-%m-%d"

template = """Answer the users qustion:
  #Format instruction:{format_instruction}
  #Qustion:{qustion}
  #Answer:"""
prompt = PromptTemplate.from_template(
    template,
    partial_variables={"format_instruction": output_parser.get_format_instructions()},
)

output_parser.get_format_instructions()

llm = ChatOpenAI(temperature=0)

chain = prompt | llm | output_parser

response= chain.invoke({"qustion": "What is the date today?"})
response

