# -*- coding: utf-8 -*-
"""07-EnumOutputParser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NHSyDuiX2-Q6wl7M_3BLNriPe8SX_11m
"""

import os

os.environ["OPENAI_API_KEY"] = "api-key"
os.environ["LANGCHAIN_API_KEY"] = "api-key"
os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGCHAIN_ENDPOINT"] = "http://api.smith.langchain.com"
os.environ["LANGCHAINPROJECT"] = "03-07"

from langchain.output_parsers.enum import EnumOutputParser
from enum import Enum

class Colors(Enum):
    RED = "빨간색"
    GREEN = "초록색"
    BLUE = "파란색"
    YELLOW = "노란색"
    ORANGE = "주황색"
    PURPLE = "보라색"
    PINK = "분홍색"
    BLACK = "검정색"
    WHITE = "흰색"
    GRAY = "회색"
    BROWN = "갈색"
    CYAN = "청록색"
    MAGENTA = "자홍색"

parser = EnumOutputParser(enum=Colors)

parser.get_format_instructions()

from langchain_core.prompts import PromptTemplate

# 색깔만 출력하도록 PromptTemplate 정의
prompt = PromptTemplate.from_template(
    """
    다음의 물체는 어떤 색깔인가요?
    Object: {object}
    Instruction: {instruction}
    응답은 반드시 다음 중 하나로만 작성하세요: ['빨간색', '초록색', '파란색', '노란색', '주황색', '보라색', '분홍색', '검정색', '흰색', '회색', '갈색', '청록색', '자홍색'].
    """
).partial(instruction="색깔만 출력하세요")

!pip install langchain_openai

from langchain_openai import ChatOpenAI
chain = prompt | ChatOpenAI(temperature=0, model='gpt-4o') | parser

response = chain.invoke({"object" : "하늘"})

print(response)