# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vPwPU7C_P2EW5pDl9BD2n_0FieaLq_8G
"""

import os
from dotenv import load_dotenv

from langchain_openai import ChatOpenAI
from langchain.output_parsers import PydanticOutputParser
from pydantic import BaseModel, Field
from langchain.output_parsers import OutputFixingParser
from typing import List

load_dotenv()

class Actor(BaseModel):
    name: str = Field(description="name of an actor")
    film_names: List[str] = Field(
        description="list of names of films they starred in")


actor_query = "Generate the filmography for a random actor."
misformatted = "{'name': 'Tom Hanks', 'film_names': ['Forrest Gump']}"

parser = PydanticOutputParser(pydantic_object=Actor)
try:
    parser.parse(base_Actor)

except:
    new_parser = OutputFixingParser.from_llm(parser=parser, llm=ChatOpenAI(model="gpt-4o"))

    final_actor = new_parser.parse(misformatted)

    print(final_actor)