# -*- coding: utf-8 -*-
"""국가별현재시간.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NjecDPLrLKe6A-1FyIJuyffXFSQ9yw1o
"""

import os

os.environ["OPENAI_API_KEY"] = "PgiMtNt9GvfIrd7XGmvwnGFkCouYoTeNx6fwidRkFh63wQf-jMa8payEdpeQIMc5Un0aBI4sEzT3BlbkFJKxEywp1498ByVF7ufO-HY8WolT5WBgjtmq3Oelr7VLUmg23s_esjxEjQ3_GcsGoBhw5vGhdz8A"
os.environ["LANGCHAIN_API_KEY"] = "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"
os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGCHAIN_ENDPOINT"] = "https://api.smith.langchain.com"
os.environ["LANGCHAIN_PROJECT"] = "01-03-2"

pip install -qU langchain_community

import random
from datetime import datetime
import pytz
from langchain.prompts import ChatPromptTemplate
from langchain.chat_models import ChatOpenAI

# 1. 나라와 해당 시간대 맵핑
NATION_TIMEZONES = {
    "Korea": "Asia/Seoul",
    "USA": "America/New_York",
    "Japan": "Asia/Tokyo",
    "Germany": "Europe/Berlin",
    "France": "Europe/Paris",
    "India": "Asia/Kolkata",
    "China": "Asia/Shanghai",
    "Brazil": "America/Sao_Paulo",
    "Australia": "Australia/Sydney",
    "Canada": "America/Toronto"
}

# 2. 랜덤 나라와 현재 시간 반환 함수
def get_random_nation_time(nations):
    nation = random.choice(nations)
    timezone = pytz.timezone(NATION_TIMEZONES[nation])
    local_time = datetime.now(timezone).strftime("%Y-%m-%d %H:%M:%S")
    return nation, local_time

# 3. ChatPromptTemplate 생성
chat_prompt = ChatPromptTemplate.from_template(
    """
    {nation}: 현재시간은 {current_time} 입니다.
    """
)

# 4. LangChain Chat 모델
chat = ChatOpenAI(model="gpt-4", temperature=0)

# 5. 메시지 생성 및 출력
nations_list = list(NATION_TIMEZONES.keys())  # 나라 리스트
messages = []

# 10개의 메시지 생성, 랜덤으로 10개 나라 고르고 중복 없이 선택
for _ in range(10):
    nation, current_time = get_random_nation_time(nations_list)
    formatted_message = chat_prompt.format(nation=nation, current_time=current_time)
    messages.append(formatted_message)
    nations_list.remove(nation)  # 선택된 나라는 목록에서 제거

# 6. 결과 출력
for message in messages:
    print(f"Human: {message}")