# -*- coding: utf-8 -*-
"""PowerpointLoader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15UCf7KEXnAIZwOECHG1KI_lIHyrbo9p3

# Microsoft PowerPoint Loader
"""

pip install -qU unstructured python-pptx langchain_community

from langchain_community.document_loaders import UnstructuredPowerPointLoader

# UnstructuredPowerPointLoader 생성
loader = UnstructuredPowerPointLoader("/content/인공지능 세미나 개요.pptx", mode = "elements")

# 데이터 로드
docs = loader.load()

# 로드한 문서의 개수 출력
print(len(docs))

docs