# -*- coding: utf-8 -*-
"""WordLoader_250106.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xjP0F44h4sMMWp-emD55m4Oq62s1IO60

# MSWord Loader
"""

pip install -qU docx2txt

pip install -qU langchain-community

from langchain_community.document_loaders import Docx2txtLoader

loader = Docx2txtLoader("/content/1차편집.docx") # 문서 로더 초기화

docs = loader.load() # 문서 로딩

print(len(docs))

docs[0].page_content

docs[0].metadata