# -*- coding: utf-8 -*-
"""03-07_EnumOutputParser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vDIVWecSF6b5fhb-s5rtpIw1mu9UrTqX
"""

import os
from dotenv import load_dotenv

from langchain.output_parsers.enum import EnumOutputParser

from enum import Enum

load_dotenv()


class Colors(Enum):
    RED = "빨간색"
    ORANGE = "주황색"
    YELLOW = "노란색"
    GREEN = "초록색"
    BLUE = "파란색"
    INDIGO = "남색"
    VIOLET = "보라색"
    WHITE = "하얀색"
    BLACK = "검은색"
    PINK = "분홍색"
    BROWN = "갈색"
    GOLD = "금색"
    SILVER = "은색"
    BRONZE = "브론즈색"

# EnumOutputParser 인스턴스 생성
parser = EnumOutputParser(enum=Colors)

from langchain_core.prompts import PromptTemplate
from langchain_openai import ChatOpenAI

# 프롬프트 템플릿을 생성합니다.
prompt = PromptTemplate.from_template(
    """다음의 단어는 어떤 색깔인가요? 그 단어의 추상적인 색깔을 선택해. 색깔만 말 해.

Object: {object}

Instructions: {instructions}"""
    # 파서에서 지시사항 형식을 가져와 부분적으로 적용합니다.
).partial(instructions=parser.get_format_instructions())

llm = ChatOpenAI(
    model="gpt-4o",
    temperature=0,

)

# 프롬프트와 ChatOpenAI, 파서를 연결합니다.
chain = prompt | llm | parser

response = chain.invoke({"object": "영국"})
print(response)