# -*- coding: utf-8 -*-
"""02.LCEL_241226_2_공남현.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hdM2wQOFO1pNr0iqF1S7IkT2-jUpQRs1

##1. API 키 가져오기
"""

import os

os.environ['OPENAI_API_KEY']=''

pip install langchain_teddynote langchain_core

from langchain_teddynote.messages import stream_response #스트리밍 출력
from langchain_core.prompts import PromptTemplate

"""# 프롬프트 정의"""

# template 정의
template = "{country}의 수도는 어디인가요?"

# form_template 메소드를 이용하여 PromptTemplate 객체 생성
prompt_template = PromptTemplate.from_template(template)
prompt_template

# prompt 생성
prompt = prompt_template.format(country="대한민국")
prompt

# prompt 생성
prompt = prompt_template.format(country="미국")
prompt

"""#모델설정"""

pip install langchain_openai

from langchain_openai import ChatOpenAI

model = ChatOpenAI(
      model ="gpt-3.5-turbo",
      max_tokens=2048,
      temperature=0.1,
)

"""#Chain 생성"""

prompt = prompt_template.from_template("{topic} 에 대해 쉽게 설명해주세요.")

model = ChatOpenAI()

chain = prompt | model

prompt

input = {"topic":"인공지능 모델의 학습 원리"}
input

chain.invoke(input)