# -*- coding: utf-8 -*-
"""ChatPromptTemplate_250113.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14iorn9wtI64iMzl9_Wi4_otdkeCbWdTw
"""

!pip install -qU langchain_openai

"""# PromptTemplate와 ChatPromptTemplate 비교"""

from langchain_core.prompts import PromptTemplate

prompt = PromptTemplate.from_template(
    '''
    [country]의 수도는 어디일까?
    '''
)

prompt

from langchain_core.prompts import ChatPromptTemplate

chat_prompt = ChatPromptTemplate.from_messages(
    [
        ("system", "너는 내용을 요악하는데 능숙한 어시스턴트야. 너의 이름은 [name]이야. 잘 대답해"),
        ("human", "반갑습니다."),
        ("ai", "안녕하세요. 무엇을 도와 드릴까요?"),
        ("human", "{user_input}"),
    ]
    )
chat_prompt

messages = chat_prompt.format_messages(
    name = "Jun", user_input = "오늘 날씨는 어때?"
)

messages

from langchain_openai import ChatOpenAI

llm  = ChatOpenAI(
    model_name = "gpt-4o",
    temperature = 0,
)

response = llm.invoke(messages)
response

chain = chat_prompt | llm
response_messages = chain.invoke({"name": "시리", "user_input": "당신의 이름은 무엇입니까?"})

response_messages

llm = ChatOpenAI()
llm.invoke(messages).content

chain = chat_template | llm
chain.invoke(messages)