# -*- coding: utf-8 -*-
"""EnumOutputParser_250117.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V8bbaGonEDMnkDHjGhZ8xSpJu8wAc44k

- **열거형 파싱**: 문자열 출력을 미리 정의된 Enum 값으로 변환
- **타입 안전성**: 파싱된 결과가 반드시 정의된 Enum 값 중 하나임을 보장
- **유연성**: 공백이나 줄바꿈 문자를 자동으로 처리
"""

!pip install -qU langchain_openai

from langchain.output_parsers.enum import EnumOutputParser
from langchain_core.prompts import PromptTemplate
from langchain_openai import ChatOpenAI

from enum import Enum

class Colors(Enum):
    RED = "빨간색"
    GREEN = "초록색"
    BLUE = "파란색"
    YELLOW = "노란색"
    BLACK = "검정색"
    WHITE = "흰색"
    ORANGE = "주황색"
    PURPLE = "보라색"
    BROWN = "갈색"
    PINK = "분홍색"
    GRAY = "회색"

# EnumOutputParser 인스턴스 생성
parser = EnumOutputParser(enum=Colors)

prompt = PromptTemplate.from_template(
    """다음의 물체는 어떤 색깔인가요?
       반드시 아래 중 하나의 색깔만 정확히 반환하세요: {valid_values}

Object: {object}

Instructions: {instructions}"""
).partial(
    instructions=parser.get_format_instructions(),
    valid_values=", ".join([color.value for color in Colors])
)

chain = prompt | ChatOpenAI(temperature = 0, model = "gpt-4o") | parser

response = chain.invoke({"object": "우주"})

response