# -*- coding: utf-8 -*-
"""langchain_hub_250114.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1falKc9rkRqJRbA6IJckFZVKC2KYaa8Ep

# 1. langchain-hub 불러오기
"""

from langchain import hub

prompt = hub.pull("rlm/rag-prompt")

prompt

"""# 2. langchain-hub 밀어넣기"""

from langchain.prompts import PromptTemplate
from langchain import hub
import os


prompt = PromptTemplate(
    input_variables=["name"],
    template="Hello {name}, how can I assist you today?"
)

from langchain import hub

hub.push('prompt_test', prompt)