# -*- coding: utf-8 -*-
"""MsgPlaceHolder_250113.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MBnr039t9ErWTPVv4jTaO_NMGTLBI514
"""

from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder

chat_prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "당신은 요악 전문 AI 어시스턴트입니다. 당신의 업무는 주요 키워드로 대화를 요약하는 것입니다."
        ),
        MessagesPlaceholder(variable_name = "conversation"),
        ("human", "지금까지의 대화를 {word_count} 단어로 요약합니다.")
    ]
)

print(chat_prompt)

formatted_chat_prompt = chat_prompt.format(
    word_count = 10,
    conversation = [
        ("human", "안녕하세요. 저는 여러분과 함께 인공지능 스터디를 수행할 황아현이라고 합니다."),
        ("ai", "반갑습니다! 앞으로 잘 부탁 드립니다.")
    ]

)

print(formatted_chat_prompt)

!pip install -qU langchain_openai

from langchain_openai import ChatOpenAI

llm = ChatOpenAI(model = 'gpt-4o', temperature = 0)

chain = chat_prompt | llm

response = chain.invoke(
    {
      "word_count": 10,
      "conversation":  [
          ("human", "안녕하세요. 저는 여러분과 함께 인공지능 스터디를 수행할 황아현이라고 합니다."),
          ("ai", "반갑습니다! 앞으로 잘 부탁 드립니다."),
          ]
    }
)