# -*- coding: utf-8 -*-
"""no_pydantic_version_250116.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1novcaedihTg7uOf7EfHef9fm6Zgfg24O
"""

!pip install -qU langchain_openai

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import JsonOutputParser
from langchain_openai import ChatOpenAI

# 질의 작성
question = "우주에 대해 알려주세요. 우주에 대한 설명은 'description' 에 관련 키워드는 'hashtags' 에 써주세요."

# JSON 출력 파서 초기화
parser = JsonOutputParser()

# 프롬프트 템플릿 설정
prompt = ChatPromptTemplate.from_messages(
    [
        ("system", "당신은 친절한 AI 어시스턴트 입니다. 질문에 간결하게 답변하세요."),
        ("user", "#Format: {format_instructions}\n\n#Question: {question}"),
    ]
)

# 지시사항을 프롬프트에 주입
prompt = prompt.partial(format_instructions = parser.get_format_instructions())

# 프롬프트, 모델, 파서를 연결하는 체인 생성
model = ChatOpenAI(temperature = 0, model_name = "gpt-4o")

# 체인을 호출하여 쿼리 실행
chain = prompt | model | parser

# 체인을 호출하여 쿼리 실행
response = chain.invoke({"question": question})

response